### ISSUE TITLE
OpenCage API key is hardcoded and does not work

### ISSUE THREAD

**Issue by andrewphilipsmith** [urbangrammarai/gee_pipeline#12]
1) The API key for OpenCage is hardcoded in the `lookup_country` function of `coordinate_utils.py`. This seems unlikely to be appropriate, as it is checked into a publically readable repo. A better option would be to read it in from an env variable or similar.

2) The API key does not work (either it is invalid or has been revoked. To reproduce:
a) run `pyveg_generate_config` without including the `--country` parameter. 
b) choose the option to look up the country name using OpenCage. 

The following error is returned:

```
Error accessing OpenCage API: b'{"documentation":"https://opencagedata.com/api","licenses":[{"name":"see attribution guide","url":"https://opencagedata.com/credits"}],"results":[],"status":{"code":401,"message":"unknown API key"},"stay_informed":{"blog":"https://blog.opencagedata.com","twitter":"https://twitter.com/OpenCage"},"thanks":"For using an OpenCage API","timestamp":{"created_http":"Fri, 15 Jul 2022 14:04:30 GMT","created_unix":1657893870},"total_results":0}'
```

**Comment by crangelsmith** [comment]
I don't think we will use this for the spatial signatures, given that we know we are mapping the UK. 

In the previous project, we had around 60 regions around the Sahel where we would fetch data between Sudan, Mali, Nigeria, etc. This was a solution to automatically get on the output metadata which country belonged to that coordinate. I guess we could fix it for future use but I don't think is a high priority.
