### ISSUE TITLE
New name

### ISSUE THREAD

**Issue by darribas** [urbangrammarai/gee_pipeline#18]
Opening thread to agree on and act on changing the name of the project since we don't do a lot of `veg` :-)

**Comment by darribas** [comment]
My vote goes to "Python Earth Engine Pipelines" (aka `peep`)

**Comment by crangelsmith** [comment]
Sounds good to me! I would say we do the name changing after we finish the first round of development for the larger scale test (issues #5, #8, #15, #22).  There is a few things that would have to go with the name change:

- [ ] Name change package but also modules
- [ ] Remove all the code not relevant for us
- [ ] Update documentation.
