### ISSUE TITLE
Adapt pyveg to work with chips arrays as outputs

### ISSUE THREAD

**Issue by crangelsmith** [urbangrammarai/gee_pipeline#5]
- [ ] Make the size of chip also part of the config file.
- [x] Save chips as .npy or .npyz files (currently .png).
- [ ] Move to eastings-northings + time range to identify the chip.
- [ ] ~Ensure that the geo-registration info for the chips is retained (currently, it is lost with the .png files).~ (moved to #22)

**Comment by andrewphilipsmith** [comment]
Closed by mistake. Reopened now.

**Comment by darribas** [comment]
Looping @martinfleis here to see if he could give us a sense on how he was working on this front. My sense is that all the chips were written into a `.npy` file and read back in memory for training. Correct?

**Comment by martinfleis** [comment]
All the chips per option (say sliced 32x32) are saved as a single `npy`. Their bounds are saved as a GeoParquet with label and information on a subset (train, validation...). So the `npy` itself does not have any spatial information but that is stored in the GeoParquet.
