### ISSUE TITLE
Map Great Britain with Polygons 

### ISSUE THREAD

**Issue by crangelsmith** [urbangrammarai/gee_pipeline#6]
Functionality to consistently and efficiently map Great Britain and create a list of polygons.

Code in here can help:

- https://urbangrammarai.xyz/signature_ai/create_chips/chips_glasgow.html

**Comment by andrewphilipsmith** [comment]
Also, create an array for storing output results aligned with the same grid.

**Comment by andrewphilipsmith** [comment]
Three key vector datasets in operation in the pipeline.

**The country boundary:**
We can check with Dani if he has a preferred source for this. But I suspect that this can be quite a simplified geometry - it just has to be detailed enough to decide if a chip is inside or outside.
In the absence of another source, this one will suffice:
https://github.com/wmgeolab/geoBoundaries/blob/main/releaseData/gbOpen/GBR/ADM0/geoBoundaries-GBR-ADM0_simplified.geojson
It would be mildly preferable to convert and store this in BNG, but it is fairly trivial to reproject on demand.

**The grid of chips**
- This should be stored in BNG.
- It should be derived procedurally, inline with BNG and the chip-width (320m?)
- Each chip ID can be derived from the easting + northing of a fixed point on the chip (eg the bottom left corner) and the chip-width. The later is required in case we re-run the pipeline with different chip-width values - the chipID should be distinct.
- Once derived it should then be clipped to the country boundary. The country boundary should be (re-)projected to BNG for this operation.
- TBD this grid could be stored as a single geodataframe, with a column pointing to the filename of each individual chip.

We will have two sister data structures representing this grid:

1. A `xarray.DataArray` (stored as a [COG](https://www.cogeo.org/) with `rioxarray`) --> Frame for _all_ predictions and uncertainty score on the inference stage
2. A `geopandas.GeoDataFrame` (stored as `GeoParquet`) with the structure: --> Maps directly on to chip objects to pass through inference

```
| ID | geometry | ... |
```

Importantly, 1. and 2. will be fully synchronised in terms of the coordinates. To get this, it might be worth to build 1. and, from there, construct 2. using the `to_series` feature in `DataArray` objects

**The grid of regions / download images**
This is the grid of images as they requested from GEE. My understanding is that pyveg represents this as a centre-point and width in degrees (the region_size parameter).
- Orientated to BNG. Squares with a fixed region_size.
- regionID - could this be generated as an aggregate of the grid-of-chips.
- The size of the regions should be optimised to have the maximum size (area), but within the GEE image size (Mb) limit.
- The grid of images should be clipped to the grid of chips. The grid of chips could be reprojected to WGS84 for this operation.
- TBD this grid could be stored as a single geodataframe, with a column pointing to the filename of each individual GEE download.

Does this make sense? I would find it helpful to agree on names for these. I’m going to suggest “chips_grid” and “images_grid” - but I’m open to better suggestions ;-)
